[package]
name = "lib_mr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis-module = { version="0.22.0", features = ["experimental-api"]}
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
libc = "0.2"

[build-dependencies]
bindgen = "0.59.2"

[lib]
crate-type = ["rlib"]
name = "mr"
path = "rust_api/lib.rs"
